caziwa/caziwa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from baton.autodiscover import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('product.urls', namespace='product')),
    url(r'^', include('index.urls')),
    url(r'^', include('users.urls')),
    url(r'^baton/', include('baton.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT)

caziwa/index/urls.py
from django.conf.urls import url
from .views import home
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^$', home, name='home'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT)

caziwa/product/urls.py
from django.conf.urls import include, url
from product.views import category_view, cataloge_view, product_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    url(r'^category/(?P<category_slug>[\w\-]+)/$', category_view, name='category'),
    url(r'^subcategory/(?P<category_slug>[\w\-]+)/(?P<subcategory_slug>[\w\-]+)/$', cataloge_view, name='subcategory'),
    url(r'^product/(?P<category_slug>[\w\-]+)/(?P<subcategory_slug>[\w\-]+)/(?P<product_id>\d+)/$', product_view, name='product'),
    # url(r'^comment/(?P<product_id>\d+)/$', comment_view, name='comment'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

caziwa/product/models.py
from django.db import models
from users.models import User, Artist
from django.utils import timezone
from django.conf import settings
from django.template.defaultfilters import slugify
from colorfield.fields import ColorField


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    image = models.ImageField(max_length=100, null=True)
    parent = models.ForeignKey('self',
                               null=True,
                               blank=True,
                               related_name='child')
    cat_slug = models.SlugField(allow_unicode=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class ProductPrice(models.Model):
    id = models.AutoField(primary_key=True)
    product = models.ForeignKey('Product', 'id', related_name="product_price")
    price = models.FloatField()
    status = models.IntegerField()
    date = models.DateTimeField()


class ProductOption(models.Model):
    id = models.AutoField(primary_key=True)
    option = models.ManyToManyField('Option')
    value = models.CharField(max_length=50)
    product = models.ForeignKey('Product', 'id')

    def __str__(self):
        return self.value


class ProductPriceOption(models.Model):
    id = models.AutoField(primary_key=True)
    product_color = models.OneToOneField('ProductColor', on_delete=models.CASCADE, default='0')
    price_diff = models.IntegerField(blank=True, default=0, null=True)


class CategoryOption(models.Model):
    id = models.AutoField(primary_key=True)
    category = models.ForeignKey('Category', 'id')
    value = models.CharField(max_length=50)
    option = models.ManyToManyField('Option')

    def __str__(self):
        return self.value


class Option(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=150)
    types = models.IntegerField(choices=())

    def __str__(self):
        return self.title


class ProductQuantity(models.Model):
    id = models.AutoField(primary_key=True)
    quantity = models.IntegerField(default=0)
    product_color = models.OneToOneField('ProductColor', on_delete=models.CASCADE, default='0')


class Product(models.Model):
    category = models.ForeignKey('Category',
                                 on_delete=models.CASCADE,
                                 null=True)
    name = models.CharField(max_length=100)
    description_short = models.CharField(max_length=200,
                                         null=True)
    description = models.TextField(null=True)
    add_date = models.DateField(null=True,
                                default=timezone.now)
    active = models.BooleanField(default=1)
    caziwa_suggest = models.BooleanField(default=False)
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('B', 'Both')
    )
    gender = models.CharField(
        "gender",
        max_length=1,
        choices=GENDER_CHOICES,
        default='B'
    )
    pic = models.ForeignKey('Image', 'id', related_name='pic', null=True, blank=True)
    artist = models.ForeignKey(Artist,
                               on_delete=models.CASCADE,
                               blank=True,
                               null=True)
    main_image = models.ImageField(null=True, )

    similars = models.ManyToManyField('Product', blank=True)


    def __str__(self):
        return self.name

    def admin_thumbnail(self):
        return u'<img src="%s" style="width:50px; height:50px;"/>' % (self.main_image.url)

    admin_thumbnail.short_description = 'Thumbnail'
    admin_thumbnail.allow_tags = True


class Image(models.Model):
    id = models.AutoField(primary_key=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_image = models.ImageField(null=True)

    class Meta:
        db_table = 'product_images'


class Comment(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    users = models.ForeignKey(settings.AUTH_USER_MODEL)
    cm_text = models.CharField(max_length=100, blank=False)
    likes = models.IntegerField(default=1)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.cm_text




class ProductSize(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_size = models.ForeignKey('Size', on_delete=models.CASCADE)

    def __str__(self):
        return self.product_size.size


class ProductColor(models.Model):
    product_size = models.ForeignKey(ProductSize, on_delete=models.CASCADE)
    product_color = models.ForeignKey('Color', on_delete=models.CASCADE)

    def __str__(self):
        return self.product_color.color_name


class Color(models.Model):
    color_name = models.CharField(blank=True, max_length=50)
    color = ColorField(default='#FF0000')

    def __str__(self):
        return self.color_name


class Size(models.Model):
    size = models.CharField(blank=True, max_length=50)

    def __str__(self):
        return self.size


class CatImage(models.Model):
    banner_one = models.ImageField(upload_to='', blank=True)
    banner_two = models.ImageField(upload_to='', blank=True)
    banner_three = models.ImageField(upload_to='', blank=True)
    banner_four = models.ImageField(upload_to='', blank=True)
    banner_five = models.ImageField(upload_to='', blank=True)
    banner_six = models.ImageField(upload_to='', blank=True)
    banner_seven = models.ImageField(upload_to='', blank=True)
    banner_eight = models.ImageField(upload_to='', blank=True)
    banner_nine = models.ImageField(upload_to='', blank=True)
    banner_ten = models.ImageField(upload_to='', blank=True)
    subcategory = models.ForeignKey('Category', on_delete=models.CASCADE)


class CatSlider(models.Model):
    slider_image = models.ImageField(upload_to='', blank=True)
    subcategory = models.ForeignKey('Category', on_delete=models.CASCADE)

caziwa/product/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import Comment, Product


class CommentForm(forms.Form):
    cm_text = forms.CharField(label='comment', max_length=500, required=False)

caziwa/product/views.py
from .models import Category, Product, ProductPrice, Comment
from django.shortcuts import render, HttpResponse,get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from product.forms import CommentForm
from django.utils import timezone
import datetime, json
from django.http import JsonResponse


def category_view(request, category_slug):
    context_dict = {}
    category = Category.objects.get(cat_slug=category_slug)
    if category.parent is not None:
        context_dict = {}
        context_dict['categories'] = Category.objects.filter(parent=None)
        return render(request, 'home.html', context=context_dict)
    else:
        context_dict['categories'] = Category.objects.filter(parent=None)
        context_dict['category'] = category
        return render(request, 'category.html', context=context_dict)


def cataloge_view(request, category_slug, subcategory_slug):
    context_dict = {}
    category = Category.objects.get(cat_slug=category_slug)
    subcategory = Category.objects.get(cat_slug=subcategory_slug)
    context_dict['category'] = category
    context_dict['subcategory'] = subcategory

    context_dict['categories'] = Category.objects.filter(parent=None)
    product_list = Product.objects.prefetch_related('product_price').filter(category=subcategory)
    page = request.GET.get('page', 1)

    paginator = Paginator(product_list, 1)
    try:
        context_dict['products'] = paginator.page(page)
    except PageNotAnInteger:
        context_dict['products'] = paginator.page(1)
    except EmptyPage:
        context_dict['products'] = paginator.page(paginator.num_pages)

    return render(request, 'catalog.html', context=context_dict)


def product_view(request, category_slug, subcategory_slug, product_id):
    context_dict = {}

    category = Category.objects.get(cat_slug=category_slug)
    subcategory = Category.objects.get(cat_slug=subcategory_slug)
    product = Product.objects.get(id=product_id)
    commnets = Comment.objects.filter(product=product).order_by('date').reverse()
    context_dict['proid'] = product_id
    context_dict['category'] = category
    context_dict['subcategory'] = subcategory
    context_dict['product'] = product
    context_dict['categories'] = Category.objects.filter(parent=None)
    context_dict['comments'] = commnets
    if request.method == 'POST' and request.is_ajax:
        form = CommentForm(request.POST)
        products = get_object_or_404(Product, pk=product_id)
        User = request.user
        if form.is_valid():
            cm_text = form.cleaned_data['cm_text']
            comment = Comment()
            comment.product = products
            comment.users = User
            comment.cm_text = cm_text
            comment.date = datetime.datetime.now()
            comment.save()
            # form.save()
            msg = "The operation has been received correctly."
            print(request.POST)

            return HttpResponse(msg)
        else:
            msg = "GET petitions are not allowed for this view."
            return HttpResponse(msg)
    else:
        form = CommentForm()
    context_dict['form'] = form

    return render(request, 'product.html', context=context_dict, )

caziwa/templates/about.html
<!DOCTYPE html> {% extends 'base.html' %} {% load static %} {% block head %}
<title>درباره ی ما</title>
<link rel="stylesheet" href="{% static 'css/about.css' %}"> {% endblock %} {% block content %}
<div class="about">
    <div class="pro-nav">
        <div class="container">
            <div class="col-sm-12">
                <ul>
                    <li><a href="#">کازیوا</a></li>
                    <li><a href="#"><b>هنرمندان</b></a></li>
                </ul>
            </div>

            <div class="clearfix"></div>
        </div>
    </div>
    <div class="content-about">
        <div class="container">
            <div class="col-sm-12">
                <div class="col-sm-3">

                </div>
                <div class="box col-sm-6">
                    <h4>مسیر کازیوا</h4>
                    <p>گستره‌ای به وسعت کالای دیجیتال (موبایل، تبلت و کتابخوان‌ها، لپ‌تاپ، کامپیوتر و لوازم جانبی، دوربین، صوتی و تصویری، ماشین‌های اداری و لوازم جانبی کالای دیجیتال)، لوازم خانگی (لوازم برقی، آشپزخانه، سرو و پذیرایی، دکوراتیو، خواب و حمام،
                        شست‌وشو و نظافت و ابزار)، زیبایی و سلامت (عطر، لوازم آرایشی، لوازم بهداشتی، لوازم شخصی برقی، ساعت، زیورآلات، ابزار سلامت)، فرهنگ و هنر (کتاب و مجلات، لوازم‌تحریر، صنایع دستی، آلات موسیقی، موسیقی، فیلم، نرم افزار و بازی و محتوای
                        آموزشی) و ورزش و سرگرمی (لوازم ورزشی، اسباب بازی، تجهیزات سفر و کفش ورزشی)؛ از برندهای متنوع، متعدد و سرشناس جهانی همچون اپل، سونی، سامسونگ، ال‌جی، اچ‌پی، کانن، بوش، نایک، آدیداس، نیوا و ... دیجی‌کالا، یک دهه پس از آغاز فعالیت،
                        با داشتن مراکز توزیع در استان تهران، امکان تحویل کالا را به‌صورت رایگان (در مورد خریدهای بیش از صدهزارتومان) در همان روز ثبت سفارش فراهم کرده است.</p>
                    </p>
                </div>
                <div class="col-sm-3">

                </div>
            </div>
            <div class="col-sm-12">
                <div class="col-md-2 col-lg-3 col-sm-1 ">

                </div>
                <div class="col-sm-10 col-md-8 col-lg-6 caziwas">
                    <div class="col-xs-12">
                        <h4>تیم کازیوا</h4>
                    </div>
                    <div class="col-xs-12 we-div">
                        <div class="col-sm-2"> </div>
                        <div class="col-sm-4 labal-lab">
                            <img src="{% static 'img/sample.jpeg' %}" alt="" class="we"> <label>سام زرین مهر</label> <label>بنیان گزار</label></div>
                        <div class="col-sm-4 labal-lab"> <img src="{% static 'img/sample.jpeg' %}" alt="" class="we"> <label>سام زرین مهر</label> <label>بنیان گزار</label> </div>
                        <div class="col-sm-2"> </div>
                    </div>
                    <div class="col-xs-12 we-div">
                        <div class="col-sm-4 labal-lab"> <img src="{% static 'img/sample.jpeg' %}" alt="" class="we"> <label>سام زرین مهر</label> <label>بنیان گزار</label> </div>
                        <div class="col-sm-4 labal-lab"> <img src="{% static 'img/sample.jpeg' %}" alt="" class="we"> <label>سام زرین مهر</label> <label>بنیان گزار</label> </div>
                        <div class="col-sm-4 labal-lab"> <img src="{% static 'img/sample.jpeg' %}" alt="" class="we"><label>سام زرین مهر</label> <label>بنیان گزار</label></div>
                    </div>
                </div>
                <div class="ol-md-2 col-lg-3 col-sm-1 ">

                </div>
            </div>
        </div>

    </div>

</div>










{% endblock%} {% block script %}
<script>

</script>
{% endblock %}

caziwa/templates/artist.html
<!DOCTYPE html> {% extends 'base.html' %} {% load static %} {% block head %}
<title>هنرمندان</title>
<link rel="stylesheet" href="{% static 'css/artist.css' %}">
<link rel="stylesheet" href="{% static 'css/hexagons.css' %}"> {% endblock %} {% block content %}
<div class="artist-pg">
    <div class="pro-nav">
        <div class="container">
            <div class="col-sm-12">
                <ul>
                    <li><a href="#">کازیوا</a></li>
                    <li><a href="#"><b>هنرمندان</b></a></li>
                </ul>
            </div>

            <div class="clearfix"></div>
        </div>
    </div>
    <div class="box-tozihat">
        <div class="col-xs-5">

        </div>
        <div class="col-xs-2">
            <a href="#" class="logo-holder">
                <img src="{% static 'img/CaziwaLogo.png' %}" class="img-responsive logo-img" alt="logo-img">
            </a>
        </div>
        <div class="col-xs-5">

        </div>
        <div class="col-sm-12">
        <div class="col-xs-2">

        </div>
        <div class="col-xs-8">
          <p>. گستره‌ای به وسعت کالای دیجیتال (موبایل، تبلت و کتابخوان‌ها، لپ‌تاپ، کامپیوتر و لوازم جانبی، دوربین، صوتی و تصویری، ماشین‌های اداری و لوازم جانبی کالای دیجیتال)، لوازم خانگی (لوازم برقی، آشپزخانه، سرو و پذیرایی، دکوراتیو، خواب و حمام، شست‌وشو و نظافت و ابزار)، زیبایی و سلامت (عطر، لوازم آرایشی، لوازم بهداشتی، لوازم شخصی برقی، ساعت، زیورآلات، ابزار سلامت)، فرهنگ و هنر (کتاب و مجلات، لوازم‌تحریر، صنایع دستی، آلات موسیقی، موسیقی، فیلم، نرم افزار و بازی و محتوای آموزشی) و ورزش و سرگرمی (لوازم ورزشی، اسباب بازی، تجهیزات سفر و کفش ورزشی)؛ از برندهای متنوع، متعدد و سرشناس جهانی همچون اپل، سونی، سامسونگ، ال‌جی، اچ‌پی، کانن، بوش، نایک، آدیداس، نیوا و ... دیجی‌کالا، یک دهه پس از آغاز فعالیت، با داشتن مراکز توزیع در استان تهران، امکان تحویل کالا را به‌صورت رایگان (در مورد خریدهای بیش از صدهزارتومان) در همان روز ثبت سفارش فراهم کرده است.</p>
        </div>
        <div class="col-xs-2">

        </div>
      </div>
    </div>
<div class="container">
  <div class="honar container">
    <p class="eng">Caziwa Artist</p>
    <p class="pers">هنرمندان کازیوا</p>
  </div>

</div>
<div class="container">
  
</div>








</div>
{% endblock%} {% block script %}
<script>

</script>
{% endblock %}

caziwa/templates/base.html
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width"> {% load static %}
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/material-design-iconic-font.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-slider.min.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/caziwa.css' %}"> -->
    <link rel="stylesheet" href="{% static 'css/bootstrap-rtl.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/font.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"> {% block head %} {% endblock %} </head>

<body>
    <!-- Navigation Bar -->
    <div class="body-wrapper">
        <div class="up-navbar">
            <div class="container">
                <div class="no-padding search-div col-sm-3 showw">
                    <div class="header-search">
                        <form method="get" action="/search">
                            <input name="search-query" type="text" size="30" placeholder="جستجو..." />
                            <i class="zmdi zmdi-search"></i>
                        </form>
                    </div>
                </div>
                <div class="col-sm-2">

                </div>
                <div class="col-sm-2 ">
                    <a href="/" class="logo-holder">
                        <img src="{% static 'img/CaziwaLogo.png' %}" class="img-responsive logo-img" alt="logo-img">
                    </a>
                </div>
                <div class="header-toggle">
                    <i class="zmdi zmdi-menu"></i>
                </div>
                <div class="col-sm-3">
                    <div class="navbar-butum">
                        <button type="button" name="button">هنرمندان در کازیوا</button>
                        <button type="button" name="button">همکاری با کازیوا</button>
                    </div>
                </div>
                <div class="col-sm-2 div-nam showw">
                    <div class="log-div no-padding">

                        {% if user.is_authenticated %}
                            <a>{{ request.user.email }}</a>
                            <form method="post" action="{% url 'logout' %}"><a href="{% url 'logout' %}" >signout</a></form>
                            {% else %}
                        <a class="reg-n-log" data-toggle="modal" data-target="#myModal">ورود</a>
                        <a class="reg-n-log" href="{%   url 'signup' %}" id="signup">ثبت نام</a>
                        {% endif %}



                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="ws-header">
            <div class="container">
                <div class="col-sm-2">

                </div>
                <div class="col-sm-8 not-pad">

                    <div class="header-left">
                        <div class="header-top">
                            <div class="header-toggle">
                                <i class="zmdi zmdi-close"></i>
                            </div>


                            <ul class="ws-main-header">
                                {% for cat in categories %}
                                <li class="ws-menu-holder"><a href="{% url 'product:category' category_slug=cat.cat_slug %}" class="ws-menu-toggle">{{ cat.name }}</a>


                                    <div class="ws-menu">

                                        <div class="col-sm-2 no-padding">
                                            <ul>
                                                {% for scat in cat.child.all %} {% if not forloop.first and forloop.counter|divisibleby:"6" %}
                                            </ul>
                                        </div>
                                        <div class="col-sm-2 no-padding">
                                            <ul>
                                                {% endif %}
                                                <li><a href="{% url 'product:subcategory' category_slug=cat.cat_slug subcategory_slug=scat.cat_slug %}">
                                                    {{ scat.name }}
                                                </a></li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                        <div class="col-sm-4 no-padding"></div>
                                        <div class="col-sm-6 no-padding">
                                            <img src="{% static 'img/logo.png' %}" class="img-responsive ws-menu-img" alt="">
                                        </div>

                                    </div>
                                </li>


                                {% endfor %}


                                <div class="clearfix"></div>


                        </div>
                        <div class="second-layer">
                            <div class="no-padding search-div col-sm-3">
                                <div class="header-search">
                                    <form method="get" action="search">
                                        <input name="search-query" type="text" size="30" placeholder="جستجو..." />
                                        <i class="zmdi zmdi-search"></i>
                                    </form>
                                </div>
                            </div>
                            <div class="col-sm-2 div-nam">
                                <div class="log-div no-padding">
                                    <a class="reg-n-log" data-toggle="modal" data-target="#myModal">ورود</a>
                                    <a class="reg-n-log" data-toggle="modal" data-target="#myModal1">ثبت نام</a>

                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <div class="header-toggle">
                                <i class="zmdi zmdi-remove"></i>
                            </div>

                        </div>
                    </div>
                </div>

                <div class="col-sm-2">

                </div>

            </div>
        </div>
        <div class="clearfix"></div>
{% include "login.html" %}
    </div>

    <!-- /Navigation Bar -->
    {% block content %} {% endblock %}
    <!-- Footer -->
    <div class="container-fluid news">
        عضویت در خبرنامه
        <form method="post" id="SubscriptionsForm" action="{% url 'subscription' %}" class="news-form">
            {% csrf_token %}
            <input name="sub_email" class="input-news" type="text" title="ایمیل خود را وارد کنید" placeholder="آدرس ایمیل" >
            <button type="submit" name="submit" class="news-btn"> ارسال</button>
        </form>
    </div>
    <div class="container footer">
        <div class="container">
            <div class="col-sm-4 col-xs-6 foot-menu-right">
                <ul>
                    <li><a> درباره ی کازیوا</a></li>
                    <li><a>تماس با کازیوا</a></li>
                    <li><a>قوانین و مقررات</a></li>
                    <li><a>فرصت های شغلی</a></li>
                </ul>

            </div>
            <div class="col-sm-4 col-xs-6 contact-div">
                <ul>
                    <li>
                        <a class="foot-email"><i class="fa fa-envelope-o" aria-hidden="true"></i>
info@caziwa.com
</a>
                    </li>
                    <li>
                        <a class="foot-phone"><i class="fa fa-phone" aria-hidden="true"></i>
۰۲۱-۶۶-۴۱-۵۸-۹۶
  </a>
                    </li>
                    <li>
                        <a class="social-med teleg-foot"><i class="fa fa-telegram" aria-hidden="true"></i></a>
                        <a class="social-med"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                        <a class="social-med"><i class="fa fa-facebook-square" aria-hidden="true"></i></a>
                    </li>
                </ul>



            </div>

            <div class="clearfix foot-clearfix"></div>

            <div class="col-sm-2 col-xs-6 portfolio-item">
                <a href="#"><img class="img-responsive" src="http://placehold.it/160x160" alt=""></a>
            </div>


            <div class="col-sm-2 col-xs-6 portfolio-item">
                <a href="#"><img class="img-responsive" src="http://placehold.it/160x160" alt=""></a>
            </div>
            <div class="clearfix"></div>


        </div>
    </div>
    <div class="clearfix">

    </div>
    <a class="cart-btn" href="/cart">
        <i class="zmdi zmdi-shopping-cart"></i>
    </a>
    <!-- /Footer -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/modernizr.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/materialize.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-slider.min.js' %}"></script>
    <script>
        $('.header-toggle').click(function() {
            $('.header-left').toggleClass('vis')
        })
        $('.cart-btn-toggle').click(function() {
            $('.cart-btn').toggleClass('vis')
        });




    </script>
<script>
    $(".contact").click(function(ev) { // for each edit contact url
        ev.preventDefault(); // prevent navigation
        var url = $(this).data("form"); // get the contact form url
        $("#contactModal").load(url, function() { // load the url into the modal
            $(this).modal('show'); // display the modal on url load
        });
        return false; // prevent the click propagation
    });

    $('.contact-form').live('submit', function() {
        $.ajax({
            type: $(this).attr('method'),
            url: this.action,
            data: $(this).serialize(),
            context: this,
            success: function(data, status) {
                $('#contactModal').html(data);
            }
        });
        return false;
    });
</script>

    {% block script %} {% endblock %}
</body>

</html>

caziwa/templates/contact.html
<!DOCTYPE html> {% extends 'base.html' %} {% load static %} {% block head %}
<title>ارتباط با ما</title>
<link rel="stylesheet" href="{% static 'css/contact.css' %}">{% endblock %} {% block content %}
<div class="contact">
    <div class="pro-nav">
        <div class="container">
            <div class="col-sm-12">
                <ul>
                    <li><a href="#">کازیوا</a></li>
                    <li><a href="#"><b>هنرمندان</b></a></li>
                </ul>
            </div>

            <div class="clearfix"></div>
        </div>
    </div>
    <div class="content-box col-sm-12 no-padding ">
        <div class="col-sm-3">

        </div>
        <div class="col-sm-6">
            <div class="col-sm-12 titr">
                کازیوا را در شبکه های مجازی دنبال کنید
            </div>
            <div class="col-sm-12">
                <div class="png">
                    <img src="{% static 'img/tel.png' %}" alt="logo">

                    <img src="{% static 'img/insta.png' %}" alt="logo">

                    <img src="{% static 'img/fb.png' %}" alt="logo">
                </div>
            </div>
            <div class="col-sm-12 information">
              <div class="half">
                شماره تماس
              </div>
              <div class="half-2">
                ۰۹۳۸۴۱۳۱۱۹۵
              </div>
            </div>
            <div class="col-sm-12 information">
              <div class="half">
                email:
              </div>
              <div class="half-2">
                caziwa@gmail.com
              </div>
            </div>
            <div class="col-sm-12 adres">
              آدرس:میدان فلسطین خیابان سرپرست پلاک ۵ طبقه ۶
            </div>
        </div>
        <div class="col-sm-3">

        </div>
        <div class="col-sm-12 photo">
          <img src="{% static 'img/tamas.png' %}" alt="">
        </div>
    </div>
</div>







{% endblock%} {% block script %}
<script>
</script>
{% endblock %}

caziwa/templates/extender.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html>

<head>
    {% block head %}
    {% endblock %}
</head>

<body>
    {% block content %}
    {% endblock %}
    {% block script %}
    {% endblock %}
</body>

</html>

caziwa/templates/profile.html
<h2>profile</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">profile</button>
</form>

caziwa/templates/subs.html
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>